export const metadata = {
    title: 'BlogsPage | Next Hero',
    description: 'Generated by create next app',
  }

import React from 'react';

const BlogsPage = () => {
    return (
        <div>
            Blogs Page
        </div>
    );
};

export default BlogsPage;